[versions]
android-gradle-plugin = "8.11.0"
androidx-compose-bom = "2025.06.01"
androidx-activity = "1.10.1"
androidx-lifecycle = "2.9.1"
androidx-wear-compose = "1.4.1"
compose = "1.8.3"
compose-compiler = "1.5.15"
kotlin = "2.0.21"
org-jetbrains-kotlinx = "1.10.2"
ktlint = "0.50.0"
horologist = "0.7.5-alpha"
robolectric = "4.15.1"
roborazzi = "1.45.1"
ui-test-junit4 = "1.8.3"

[libraries]
android-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
android-desugarjdklibs = "com.android.tools:desugar_jdk_libs:2.1.5"
android-lint-gradle = "com.android.tools.lint:lint-gradle:31.11.0"
android-material = "com.google.android.material:material:1.12.0"
android-tools-lint-gradle = "com.android.tools.lint:lint-gradle:31.11.0"
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-appcompat = "androidx.appcompat:appcompat:1.7.1"
androidx-compose-ui-tooling = { module = "androidx.wear.compose:compose-ui-tooling", version.ref = "androidx-wear-compose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-fragment-ktx = "androidx.fragment:fragment-ktx:1.8.8"
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-wear = "androidx.wear:wear:1.3.0"
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest"}
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "ui-test-junit4" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
horologist-compose-layout = { group = "com.google.android.horologist", name = "horologist-compose-layout", version.ref = "horologist" }
horologist-roboscreenshots = { module = "com.google.android.horologist:horologist-roboscreenshots", version.ref = "horologist" }
junit = "junit:junit:4.13.2"
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "org-jetbrains-kotlinx" }
playservices-wearable = "com.google.android.gms:play-services-wearable:19.0.0"
wear-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "androidx-wear-compose" }
wear-compose-material = { module = "androidx.wear.compose:compose-material", version.ref = "androidx-wear-compose" }
wear-compose-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "androidx-wear-compose" }
wear-phone-interactions = "androidx.wear:wear-phone-interactions:1.1.0"
wear-remote-interactions = "androidx.wear:wear-remote-interactions:1.1.0"
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
roborazzi = { group = "io.github.takahirom.roborazzi", name = "roborazzi", version.ref = "roborazzi" }
roborazzi-compose = { group = "io.github.takahirom.roborazzi", name = "roborazzi-compose", version.ref = "roborazzi" }
roborazzi-rule = { group = "io.github.takahirom.roborazzi", name = "roborazzi-junit-rule", version.ref = "roborazzi" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
com-android-test = { id = "com.android.test", version.ref = "android-gradle-plugin" }
com-diffplug-spotless = "com.diffplug.spotless:7.0.4"
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }
