[versions]
android-gradle-plugin = "7.2.1"
androidx-activity = "1.5.0"
androidx-lifecycle = "2.5.0"
androidx-test = "1.4.0"
androidx-wear-compose = "1.0.0-alpha21"
androidx-wear-tiles = "1.0.1"
androidx-wear-watchface = "1.0.1"
compose = "1.2.0-alpha08"
ktlint = "0.41.0"
org-jetbrains-kotlin = "1.7.10"
org-jetbrains-kotlinx = "1.6.3"

[libraries]
android-lint-gradle = "com.android.tools.lint:lint-gradle:30.2.1"
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-appcompat = "androidx.appcompat:appcompat:1.4.2"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-core-ktx = "androidx.core:core-ktx:1.8.0"
androidx-databinding-viewbinding = "androidx.databinding:viewbinding:7.2.1"
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-wear = "androidx.wear:wear:1.2.0"
jacoco-ant = "org.jacoco:org.jacoco.ant:0.8.8"
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "org-jetbrains-kotlinx" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "org-jetbrains-kotlinx" }
playservices-wearable = "com.google.android.gms:play-services-wearable:17.1.0"
wear-phone-interactions = "androidx.wear:wear-phone-interactions:1.1.0-alpha03"
wear-remote-interactions = "androidx.wear:wear-remote-interactions:1.0.0"

[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
com-diffplug-spotless = "com.diffplug.spotless:6.7.2"
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin" }
