[versions]
android-gradle-plugin = "7.4.2"
androidx-activity = "1.4.0"
androidx-lifecycle = "2.5.1"
androidx-test = "1.4.0"
androidx-wear-compose = "1.1.0-rc01"
androidx-wear-tiles = "1.0.1"
androidx-wear-watchface = "1.1.1"
compose = "1.3.1"
ktlint = "0.46.1"
org-jetbrains-kotlin = "1.8.10"
org-jetbrains-kotlinx = "1.6.4"

[libraries]
android-lint-gradle = "com.android.tools.lint:lint-gradle:31.0.1"
androidx-core-ktx = "androidx.core:core-ktx:1.10.0"
androidx-databinding-viewbinding = "androidx.databinding:viewbinding:8.0.1"
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.0.0"
androidx-wear-watchface-complications-data-source-ktx = { module = "androidx.wear.watchface:watchface-complications-data-source-ktx", version.ref = "androidx-wear-watchface" }
jacoco-ant = "org.jacoco:org.jacoco.ant:0.8.10"
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
kotlin-parcelize-compiler = { module = "org.jetbrains.kotlin:kotlin-parcelize-compiler", version.ref = "org-jetbrains-kotlin" }
kotlin-parcelize-runtime = { module = "org.jetbrains.kotlin:kotlin-parcelize-runtime", version.ref = "org-jetbrains-kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "org-jetbrains-kotlinx" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
com-diffplug-spotless = "com.diffplug.spotless:6.18.0"
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin" }
