[versions]
android-gradle-plugin = "7.1.3"
androidx-activity = "1.4.0"
androidx-lifecycle = "2.4.1"
androidx-test = "1.4.0"
androidx-wear-compose = "1.0.0-alpha21"
compose = "1.2.0-alpha08"
ktlint = "0.41.0"
org-jetbrains-kotlin = "1.6.20"
org-jetbrains-kotlinx = "1.6.1"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-core-ktx = "androidx.core:core-ktx:1.7.0"
androidx-databinding-viewbinding = "androidx.databinding:viewbinding:7.2.0"
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-wear = "androidx.wear:wear:1.2.0"
androidx-window = "androidx.window:window:1.0.0"
com-google-truth = "com.google.truth:truth:1.1.3"
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
jacoco-ant = "org.jacoco:org.jacoco.ant:0.8.8"
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "org-jetbrains-kotlinx" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "org-jetbrains-kotlinx" }
test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
test-espresso-core = "androidx.test.espresso:espresso-core:3.4.0"
test-ext-junit = "androidx.test.ext:junit:1.1.3"
test-ext-junit-ktx = "androidx.test.ext:junit-ktx:1.1.3"
test-ext-truth = "androidx.test.ext:truth:1.4.0"
test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
test-uiautomator = "androidx.test.uiautomator:uiautomator:2.2.0"
wear-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "androidx-wear-compose" }
wear-compose-material = { module = "androidx.wear.compose:compose-material", version.ref = "androidx-wear-compose" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
com-diffplug-spotless = "com.diffplug.spotless:6.5.2"
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin" }
