[versions]
android-gradle-plugin = "8.2.2"
androidx-activity = "1.8.2"
androidx-compose-bom = "2024.02.01"
androidx-lifecycle = "2.7.0"
androidx-wear-compose = "1.3.0"
compose-compiler = "1.5.10"
compose-ui-tooling = "1.3.0"
horologist-compose-layout = "0.5.22"
ktlint = "0.50.0"
org-jetbrains-kotlin = "1.9.22"
org-jetbrains-kotlinx = "1.8.0"
wearable = "2.9.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-compose-ui-tooling = { module = "androidx.wear.compose:compose-ui-tooling", version.ref = "compose-ui-tooling" }
androidx-core-ktx = "androidx.core:core-ktx:1.12.0"
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-wear = "androidx.wear:wear:1.3.0"
androidx-window = "androidx.window:window:1.2.0"
com-google-truth = "com.google.truth:truth:1.4.1"
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
horologist-compose-layout = { module = "com.google.android.horologist:horologist-compose-layout", version.ref = "horologist-compose-layout" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "org-jetbrains-kotlinx" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "org-jetbrains-kotlinx" }
test-core = "androidx.test:core:1.5.0"
test-core-ktx = "androidx.test:core-ktx:1.5.0"
test-espresso-core = "androidx.test.espresso:espresso-core:3.5.1"
test-ext-junit = "androidx.test.ext:junit:1.1.5"
test-ext-junit-ktx = "androidx.test.ext:junit-ktx:1.1.5"
test-ext-truth = "androidx.test.ext:truth:1.5.0"
test-rules = "androidx.test:rules:1.5.0"
test-runner = "androidx.test:runner:1.5.2"
test-uiautomator = "androidx.test.uiautomator:uiautomator:2.3.0"
wear-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "androidx-wear-compose" }
wear-compose-material = { module = "androidx.wear.compose:compose-material", version.ref = "androidx-wear-compose" }
wearable = { module = "com.google.android.wearable:wearable", version.ref = "wearable" }
desugar-jdk-libs = "com.android.tools:desugar_jdk_libs:2.0.4"

[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
com-diffplug-spotless = "com.diffplug.spotless:6.25.0"
firebase-testlab = "com.google.firebase.testlab:0.0.1-alpha06"
