name: AlwaysOnKotlin

on:
  push:
    branches:
      - main
    paths:
      - 'AlwaysOnKotlin/**'
      - '.github/workflows/AlwaysOnKotlin.yml'
  pull_request:
    paths:
      - 'AlwaysOnKotlin/**'
      - '.github/workflows/AlwaysOnKotlin.yml'

env:
  SAMPLE_PATH: AlwaysOnKotlin

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: ${{ env.SAMPLE_PATH }}

      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check --stacktrace
          build-root-directory: ${{ env.SAMPLE_PATH }}

      - name: Upload views build outputs (APKs)
        uses: actions/upload-artifact@v3
        with:
          name: build-outputs
          path: ${{ env.SAMPLE_PATH }}/views/build/outputs

      - name: Upload views build reports
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: ${{ env.SAMPLE_PATH }}/views/build/reports

      - name: Upload compose build outputs (APKs)
        uses: actions/upload-artifact@v3
        with:
          name: build-outputs
          path: ${{ env.SAMPLE_PATH }}/compose/build/outputs

      - name: Upload compose build reports
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: ${{ env.SAMPLE_PATH }}/compose/build/reports

  android-test:
    runs-on: macos-latest # enables hardware acceleration in the virtual machine
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        device:
          - roundApi28
          - roundApi30
          - roundApi33

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pulseaudio
        run: brew install pulseaudio

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Accept licenses
        run: |
          mkdir -p /Users/runner/Library/Android/sdk/licenses
          echo 84831b9409646a918e30573bab4c9c91346d8abd > /Users/runner/Library/Android/sdk/licenses/android-sdk-preview-license

      - name: Run instrumentation tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ matrix.device }}Check
            -Dorg.gradle.workers.max=1
            -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect
            -Pandroid.experimental.testOptions.managedDevices.setupTimeoutMinutes=180
            -Pandroid.experimental.androidTest.numManagedDeviceShards=1
            -Pandroid.experimental.testOptions.managedDevices.maxConcurrentDevices=1
            -Pandroid.experimental.testOptions.managedDevices.emulator.showKernelLogging=true
            --stacktrace
          build-root-directory: ${{ env.SAMPLE_PATH }}

      - name: Upload views test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: ${{ env.SAMPLE_PATH }}/views/build/reports

      - name: Upload compose test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: ${{ env.SAMPLE_PATH }}/compose/build/reports

  apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: compose:assembleRelease
          build-root-directory: ${{ env.SAMPLE_PATH }}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: App
          path: ${{ env.SAMPLE_PATH }}/compose/build/outputs/apk/release/compose-release.apk
