name: AlwaysOnKotlin

on:
  push:
    branches:
      - main
    paths:
      - 'AlwaysOnKotlin/**'
  pull_request:
    paths:
      - 'AlwaysOnKotlin/**'

env:
  SAMPLE_PATH: AlwaysOnKotlin

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Generate cache key
        run: ./scripts/checksum.sh $SAMPLE_PATH checksum.txt

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('checksum.txt') }}

      - name: Build project
        working-directory: ${{ env.SAMPLE_PATH }}
        run: ./gradlew check --stacktrace

      - name: Upload views build outputs (APKs)
        uses: actions/upload-artifact@v2
        with:
          name: build-outputs
          path: ${{ env.SAMPLE_PATH }}/views/build/outputs

      - name: Upload views build reports
        uses: actions/upload-artifact@v2
        with:
          name: build-reports
          path: ${{ env.SAMPLE_PATH }}/views/build/reports

      - name: Upload compose build outputs (APKs)
        uses: actions/upload-artifact@v2
        with:
          name: build-outputs
          path: ${{ env.SAMPLE_PATH }}/compose/build/outputs

      - name: Upload compose build reports
        uses: actions/upload-artifact@v2
        with:
          name: build-reports
          path: ${{ env.SAMPLE_PATH }}/compose/build/reports

  android-test:
    needs: build
    runs-on: macOS-latest # enables hardware acceleration in the virtual machine
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        profile: [ wear_round, wear_square ]
        api-level: [ 26, 28, 30 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Generate cache key
        run: ./scripts/checksum.sh $SAMPLE_PATH checksum.txt

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('checksum.txt') }}

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          profile: ${{ matrix.profile }}
          target: android-wear
          force-avd-creation: false
          avd-name: test
          disable-animations: true
          script: ./gradlew connectedCheck --stacktrace
          working-directory: ${{ env.SAMPLE_PATH }}

      - name: Upload views test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: ${{ env.SAMPLE_PATH }}/views/build/reports

      - name: Upload compose test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: ${{ env.SAMPLE_PATH }}/compose/build/reports
