name: WearTilesKotlin

on:
  push:
    branches:
      - main
    paths:
      - 'WearTilesKotlin/**'
  pull_request:
    paths:
      - 'WearTilesKotlin/**'

env:
  SAMPLE_PATH: WearTilesKotlin

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        working-directory: ${{ env.SAMPLE_PATH }}

      - name: Build project
        working-directory: ${{ env.SAMPLE_PATH }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check --stacktrace

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v3
        with:
          name: build-outputs
          path: ${{ env.SAMPLE_PATH }}/app/build/outputs

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: ${{ env.SAMPLE_PATH }}/app/build/reports
