name: WearTilesKotlin

on:
  push:
    branches:
      - main
    paths:
      - 'WearTilesKotlin/**'
      - '.github/workflows/WearTilesKotlin.yml'
  pull_request:
    paths:
      - 'WearTilesKotlin/**'
      - '.github/workflows/WearTilesKotlin.yml'

env:
  SAMPLE_PATH: WearTilesKotlin

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          build-root-directory: ${{ env.SAMPLE_PATH }}

      - name: Build project
        working-directory: ${{ env.SAMPLE_PATH }}
        uses: gradle/gradle-build-action@v3
        with:
          arguments: check --stacktrace
          build-root-directory: ${{ env.SAMPLE_PATH }}

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs
          path: ${{ env.SAMPLE_PATH }}/app/build/outputs

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: ${{ env.SAMPLE_PATH }}/app/build/reports
