[versions]
android-gradle-plugin = "8.8.0"
androidx-wear-tiles = "1.5.0-alpha08" # https://developer.android.com/jetpack/androidx/releases/wear-tiles
androidx-wear-proto = "1.3.0-alpha08"
compose = "1.7.8"
compose-compiler = "1.5.15"
concurrent-futures = "1.2.0"
horologist = "0.7.5-alpha"
ktlint = "0.50.0"
org-jetbrains-kotlin = "2.1.10"
org-jetbrains-kotlinx = "1.10.1"

[libraries]
androidx-concurrent-futures = { module = "androidx.concurrent:concurrent-futures", version.ref = "concurrent-futures" }
androidx-datastore = "androidx.datastore:datastore-preferences:1.1.2"
androidx-lifecycle-runtime-ktx = "androidx.lifecycle:lifecycle-runtime-ktx:2.8.7"
androidx-lifecycle-viewmodel-ktx = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7"
androidx-protolayout-material3 = { module = "androidx.wear.protolayout:protolayout-material3", version.ref = "androidx-wear-proto" }
androidx-tiles = { module = "androidx.wear.tiles:tiles", version.ref = "androidx-wear-tiles" }
androidx-tiles-renderer = { module = "androidx.wear.tiles:tiles-renderer", version.ref = "androidx-wear-tiles" }
androidx-tiles-tooling = { module = "androidx.wear.tiles:tiles-tooling", version.ref = "androidx-wear-tiles" }
androidx-tiles-tooling-preview = { module = "androidx.wear.tiles:tiles-tooling-preview", version.ref = "androidx-wear-tiles" }
coil = "io.coil-kt:coil-compose:2.7.0"
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
horologist-compose-tools = { module = "com.google.android.horologist:horologist-compose-tools", version.ref = "horologist" }
horologist-tiles = { module = "com.google.android.horologist:horologist-tiles", version.ref = "horologist" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "org-jetbrains-kotlinx" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "org-jetbrains-kotlinx" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
desugar-jdk-libs = "com.android.tools:desugar_jdk_libs:2.1.3"

[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
com-diffplug-spotless = "com.diffplug.spotless:7.0.2"
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "org-jetbrains-kotlin" }
