[versions]
android-gradle-plugin = "8.10.1"
compose = "1.8.2"
compose-compiler = "1.5.15"
ktlint = "0.50.0"
ktfmt = "0.54"
androidx-wear-tiles = "1.5.0"
androidx-wear-proto = "1.3.0"
coil = "3.2.0"
horologist = "0.7.12-alpha"
org-jetbrains-kotlin = "2.1.21"
wear-tooling-preview = "1.0.0"

[libraries]
androidx-protolayout-material = { module = "androidx.wear.protolayout:protolayout-material", version.ref = "androidx-wear-proto" }
androidx-protolayout-material3 = { module = "androidx.wear.protolayout:protolayout-material3", version.ref = "androidx-wear-proto" }
androidx-tiles = { module = "androidx.wear.tiles:tiles", version.ref = "androidx-wear-tiles" }
androidx-tiles-renderer = { module = "androidx.wear.tiles:tiles-renderer", version.ref = "androidx-wear-tiles" }
androidx-tiles-tooling = { module = "androidx.wear.tiles:tiles-tooling", version.ref = "androidx-wear-tiles" }
androidx-tiles-tooling-preview = { module = "androidx.wear.tiles:tiles-tooling-preview", version.ref = "androidx-wear-tiles" }
androidx-wear-tooling-preview = { module = "androidx.wear:wear-tooling-preview", version.ref = "wear-tooling-preview" }
coil3-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
coil3-coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
horologist-tiles = { module = "com.google.android.horologist:horologist-tiles", version.ref = "horologist" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
desugar-jdk-libs = "com.android.tools:desugar_jdk_libs:2.1.5"

[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
com-diffplug-spotless = "com.diffplug.spotless:7.0.4"
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "org-jetbrains-kotlin" }
