[versions]
androidx-activity = "1.4.0"
androidx-lifecycle = "2.4.1"
androidx-test = "1.4.0"
androidx-wear-compose = "1.0.0-alpha17"
androidx-wear-tiles = "1.1.0-alpha03"
androidx-wear-watchface = "1.0.1"
compose = "1.2.0-alpha04"
org-jetbrains-kotlin = "1.6.10"
org-jetbrains-kotlinx = "1.6.0"
ktlint = "0.41.0"

[libraries]
android-build-gradle = "com.android.tools.build:gradle:7.1.1"
android-desugarjdklibs = "com.android.tools:desugar_jdk_libs:1.1.5"
android-lint-gradle = "com.android.tools.lint:lint-gradle:30.1.1"
android-material = "com.google.android.material:material:1.5.0"
android-tools-lint-gradle = "com.android.tools.lint:lint-gradle:30.1.1"
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-appcompat = "androidx.appcompat:appcompat:1.4.1"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.3"
androidx-constraintlayout-compose = "androidx.constraintlayout:constraintlayout-compose:1.0.0"
androidx-core-ktx = "androidx.core:core-ktx:1.7.0"
androidx-databinding-viewbinding = "androidx.databinding:viewbinding:7.1.1"
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.0.0"
androidx-fragment-ktx = "androidx.fragment:fragment-ktx:1.4.1"
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }
androidx-media = "androidx.media:media:1.5.0"
androidx-wear = "androidx.wear:wear:1.2.0"
androidx-wear-watchface-complications-data-source-ktx = "androidx.wear.watchface:watchface-complications-data-source-ktx:1.0.1"
androidx-window = "androidx.window:window:1.0.0"
com-google-truth = "com.google.truth:truth:1.1.3"
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-material-ripple = { module = "androidx.compose.material:material-ripple", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
jacoco-ant = "org.jacoco:org.jacoco.ant:0.8.7"
junit = "junit:junit:4.13.2"
kotlin-annotation-processing-gradle = { module = "org.jetbrains.kotlin:kotlin-annotation-processing-gradle", version.ref = "org-jetbrains-kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
kotlin-parcelize-compiler = { module = "org.jetbrains.kotlin:kotlin-parcelize-compiler", version.ref = "org-jetbrains-kotlin" }
kotlin-parcelize-runtime = { module = "org.jetbrains.kotlin:kotlin-parcelize-runtime", version.ref = "org-jetbrains-kotlin" }
kotlin-scripting-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable", version.ref = "org-jetbrains-kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "org-jetbrains-kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "org-jetbrains-kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "org-jetbrains-kotlinx" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "org-jetbrains-kotlinx" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "org-jetbrains-kotlinx" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "org-jetbrains-kotlinx" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "org-jetbrains-kotlinx" }
org-robolectric = "org.robolectric:robolectric:4.7.3"
playservices-auth = "com.google.android.gms:play-services-auth:20.1.0"
playservices-wearable = "com.google.android.gms:play-services-wearable:17.1.0"
test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
test-espresso-core = "androidx.test.espresso:espresso-core:3.4.0"
test-ext-junit = "androidx.test.ext:junit:1.1.3"
test-ext-junit-ktx = "androidx.test.ext:junit-ktx:1.1.3"
test-ext-truth = "androidx.test.ext:truth:1.4.0"
test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
test-uiautomator = "androidx.test.uiautomator:uiautomator:2.2.0"
wear-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "androidx-wear-compose" }
wear-compose-material = { module = "androidx.wear.compose:compose-material", version.ref = "androidx-wear-compose" }
wear-compose-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "androidx-wear-compose" }
wear-phone-interactions = "androidx.wear:wear-phone-interactions:1.1.0-alpha02"
wear-remote-interactions = "androidx.wear:wear-remote-interactions:1.0.0"
wear-tiles = { module = "androidx.wear.tiles:tiles", version.ref = "androidx-wear-tiles" }
wear-tiles-material = { module = "androidx.wear.tiles:tiles-material", version.ref = "androidx-wear-tiles" }
wear-tiles-renderer = { module = "androidx.wear.tiles:tiles-renderer", version.ref = "androidx-wear-tiles" }
wear-watchface = { module = "androidx.wear.watchface:watchface", version.ref = "androidx-wear-watchface" }
wear-watchface-client = { module = "androidx.wear.watchface:watchface-client", version.ref = "androidx-wear-watchface" }
wear-watchface-complications-data = { module = "androidx.wear.watchface:watchface-complications-data", version.ref = "androidx-wear-watchface" }
wear-watchface-complications-data-source = { module = "androidx.wear.watchface:watchface-complications-data-source", version.ref = "androidx-wear-watchface" }
wear-watchface-complications-rendering = { module = "androidx.wear.watchface:watchface-complications-rendering", version.ref = "androidx-wear-watchface" }
wear-watchface-data = { module = "androidx.wear.watchface:watchface-data", version.ref = "androidx-wear-watchface" }
wear-watchface-editor = { module = "androidx.wear.watchface:watchface-editor", version.ref = "androidx-wear-watchface" }
wear-watchface-style = { module = "androidx.wear.watchface:watchface-style", version.ref = "androidx-wear-watchface" }

[plugins]
android = "android:7.1.1"
android-library = "android-library:7.1.1"
android-reporting = "android-reporting:7.1.1"
com-android-application = "com.android.application:7.1.1"
com-android-asset-pack = "com.android.asset-pack:7.1.1"
com-android-asset-pack-bundle = "com.android.asset-pack-bundle:7.1.1"
com-android-base = "com.android.base:7.1.1"
com-android-dynamic-feature = "com.android.dynamic-feature:7.1.1"
com-android-internal-application = "com.android.internal.application:7.1.1"
com-android-internal-asset-pack = "com.android.internal.asset-pack:7.1.1"
com-android-internal-asset-pack-bundle = "com.android.internal.asset-pack-bundle:7.1.1"
com-android-internal-dynamic-feature = "com.android.internal.dynamic-feature:7.1.1"
com-android-internal-library = "com.android.internal.library:7.1.1"
com-android-internal-reporting = "com.android.internal.reporting:7.1.1"
com-android-internal-test = "com.android.internal.test:7.1.1"
com-android-internal-version-check = "com.android.internal.version-check:7.1.1"
com-android-library = "com.android.library:7.1.1"
com-android-lint = "com.android.lint:7.1.1"
com-android-reporting = "com.android.reporting:7.1.1"
com-android-test = "com.android.test:7.1.1"
com-diffplug-spotless = "com.diffplug.spotless:6.3.0"
kotlin = "kotlin:1.6.10"
kotlin-android = "kotlin-android:1.6.10"
kotlin-android-extensions = "kotlin-android-extensions:1.6.10"
kotlin-dce-js = "kotlin-dce-js:1.6.10"
kotlin-kapt = "kotlin-kapt:1.6.10"
kotlin-multiplatform = "kotlin-multiplatform:1.6.10"
kotlin-native-cocoapods = "kotlin-native-cocoapods:1.6.10"
kotlin-native-performance = "kotlin-native-performance:1.6.10"
kotlin-parcelize = "kotlin-parcelize:1.6.10"
kotlin-platform-android = "kotlin-platform-android:1.6.10"
kotlin-platform-common = "kotlin-platform-common:1.6.10"
kotlin-platform-js = "kotlin-platform-js:1.6.10"
kotlin-platform-jvm = "kotlin-platform-jvm:1.6.10"
kotlin-scripting = "kotlin-scripting:1.6.10"
kotlin2js = "kotlin2js:1.6.10"
org-jetbrains-kotlin-android = "org.jetbrains.kotlin.android:1.6.10"
org-jetbrains-kotlin-android-extensions = "org.jetbrains.kotlin.android.extensions:1.6.10"
org-jetbrains-kotlin-js = "org.jetbrains.kotlin.js:1.6.10"
org-jetbrains-kotlin-jvm = "org.jetbrains.kotlin.jvm:1.6.10"
org-jetbrains-kotlin-kapt = "org.jetbrains.kotlin.kapt:1.6.10"
org-jetbrains-kotlin-multiplatform = "org.jetbrains.kotlin.multiplatform:1.6.10"
org-jetbrains-kotlin-multiplatform-pm20 = "org.jetbrains.kotlin.multiplatform.pm20:1.6.10"
org-jetbrains-kotlin-native-cocoapods = "org.jetbrains.kotlin.native.cocoapods:1.6.10"
org-jetbrains-kotlin-native-performance = "org.jetbrains.kotlin.native.performance:1.6.10"
org-jetbrains-kotlin-platform-android = "org.jetbrains.kotlin.platform.android:1.6.10"
org-jetbrains-kotlin-platform-common = "org.jetbrains.kotlin.platform.common:1.6.10"
org-jetbrains-kotlin-platform-js = "org.jetbrains.kotlin.platform.js:1.6.10"
org-jetbrains-kotlin-platform-jvm = "org.jetbrains.kotlin.platform.jvm:1.6.10"
org-jetbrains-kotlin-plugin-parcelize = "org.jetbrains.kotlin.plugin.parcelize:1.6.10"
org-jetbrains-kotlin-plugin-scripting = "org.jetbrains.kotlin.plugin.scripting:1.6.10"
