[versions]
android-gradle-plugin = "7.2.1"
androidx-activity = "1.4.0"
androidx-lifecycle = "2.4.1"
androidx-test = "1.4.0"
androidx-wear-compose = "1.0.0"
androidx-wear-tiles = '1.1.0-beta01'
compose = "1.2.0"
compose-compiler = "1.2.0"
horologist = "0.1.0"
ktlint = "0.41.0"
org-jetbrains-kotlin = "1.7.10"
org-jetbrains-kotlinx = "1.6.4"

[libraries]
android-lint-gradle = "com.android.tools.lint:lint-gradle:30.2.1"
androidx-activity-compose = "androidx.activity:activity-compose:1.5.1"
androidx-datastore = "androidx.datastore:datastore-preferences:1.0.0"
androidx-wear = "androidx.wear:wear:1.2.0"
androidx-wear-compose = { module = "androidx.wear.compose:compose-foundation", version.ref = "androidx-wear-compose"}
androidx-wear-compose-material = { module = "androidx.wear.compose:compose-material", version.ref = "androidx-wear-compose"}
androidx-wear-tiles = { module = "androidx.wear.tiles:tiles", version.ref = "androidx-wear-tiles" }
androidx-wear-tiles-material = { module = "androidx.wear.tiles:tiles-material", version.ref = "androidx-wear-tiles" }
androidx-wear-tiles-renderer = { module = "androidx.wear.tiles:tiles-renderer", version.ref = "androidx-wear-tiles" }
coil = "io.coil-kt:coil-compose:2.1.0"
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
horologist-compose-layout = { module = "com.google.android.horologist:horologist-compose-layout", version.ref = "horologist" }
horologist-compose-tools = { module = "com.google.android.horologist:horologist-compose-tools", version.ref = "horologist" }
horologist-tiles = { module = "com.google.android.horologist:horologist-tiles", version.ref = "horologist" }
jacoco-ant = "org.jacoco:org.jacoco.ant:0.8.8"
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "org-jetbrains-kotlinx" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "org-jetbrains-kotlinx" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
com-diffplug-spotless = "com.diffplug.spotless:6.7.2"
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin" }
