[versions]
android-gradle-plugin = "8.0.2"
androidx-test = "1.4.0"
androidx-wear-tiles = "1.1.0"
compose = "1.4.3"
compose-compiler = "1.4.7"
horologist = "0.5.0"
ktlint = "0.46.1"
org-jetbrains-kotlin = "1.8.21"
org-jetbrains-kotlinx = "1.7.2"

[libraries]
android-lint-gradle = "com.android.tools.lint:lint-gradle:31.0.2"
androidx-datastore = "androidx.datastore:datastore-preferences:1.0.0"
androidx-lifecycle-runtime-ktx = "androidx.lifecycle:lifecycle-runtime-ktx:2.6.1"
androidx-lifecycle-viewmodel-ktx = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1"
androidx-wear-tiles = { module = "androidx.wear.tiles:tiles", version.ref = "androidx-wear-tiles" }
androidx-wear-tiles-material = { module = "androidx.wear.tiles:tiles-material", version.ref = "androidx-wear-tiles" }
coil = "io.coil-kt:coil-compose:2.4.0"
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
horologist-compose-tools = { module = "com.google.android.horologist:horologist-compose-tools", version.ref = "horologist" }
horologist-tiles = { module = "com.google.android.horologist:horologist-tiles", version.ref = "horologist" }
jacoco-ant = "org.jacoco:org.jacoco.ant:0.8.10"
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "org-jetbrains-kotlinx" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "org-jetbrains-kotlinx" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
com-diffplug-spotless = "com.diffplug.spotless:6.18.0"
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin" }
